git-debimport mdadm_3.2.5-5.debian.tar.bz2

diff --git a/debian/checkarray b/debian/checkarray
--- a/debian/checkarray
+++ b/debian/checkarray
@@ -11,46 +11,42 @@ PROGNAME=${0##*/}
 
 about()
 {
-  echo "$PROGNAME -- MD array (RAID) redundancy checker tool"
-  echo "Copyright © martin f. krafft <madduck@debian.org>"
-  echo "Released under the terms of the Artistic Licence 2.0"
+  echo "\
+$PROGNAME -- MD array (RAID) redundancy checker tool
+Copyright © martin f. krafft <madduck@debian.org>
+Released under the terms of the Artistic Licence 2.0"
 }
 
 usage()
 {
   about
-  echo
-  echo "Usage: $PROGNAME [options] [arrays]"
-  echo
-  echo "Valid options are:"
-  cat <<-_eof | column -s\& -t
-	-a|--all & check all assembled arrays (check /proc/mdstat).
-	-s|--status & print redundancy check status of devices.
-	-x|--cancel & queue a request to cancel a running redundancy check.
-	-i|--idle & perform check in a lowest I/O scheduling class (idle).
-	-l|--slow & perform check in a lower-than-standard I/O scheduling class.
-	-f|--fast & perform check in higher-than-standard I/O scheduling class.
-	--realtime & perform check in real-time I/O scheduling class (DANGEROUS!).
-	-c|--cron & honour AUTOCHECK setting in /etc/default/mdadm.
-	-q|--quiet & suppress informational messages.
-	-Q|--real-quiet & suppress all output messages, including warnings and errors.
-	-h|--help & show this output.
-	-V|--version & show version information.
-	_eof
-  echo
-  echo "Examples:"
-  echo "  $PROGNAME --all --idle"
-  echo "  $PROGNAME --quiet /dev/md[123]"
-  echo "  $PROGNAME -sa"
-  echo "  $PROGNAME -x --all"
-  echo
-  echo "Devices can be specified in almost any format. The following are"
-  echo "all equivalent:"
-  echo "  /dev/md0, md0, /dev/md/0, /sys/block/md0"
-  echo
-  echo "The --all option overrides all arrays passed to the script."
-  echo
-  echo "You can also control the status of a check with /proc/mdstat ."
+  echo "
+Usage: $PROGNAME [options] [arrays]
+
+Valid options are:
+ -a|--all	check all assembled arrays (ignores arrays in command line).
+ -s|--status	print redundancy check status of devices.
+ -x|--cancel	queue a request to cancel a running redundancy check.
+ -i|--idle	perform check in a lowest scheduling class (idle)
+ -l|--slow	perform check in a lower-than-standard scheduling class
+ -f|--fast	perform check in higher-than-standard scheduling class
+ --realtime	perform check in real-time scheduling class (DANGEROUS!)
+ -c|--cron	honour AUTOCHECK setting in /etc/default/mdadm.
+ -q|--quiet	suppress informational messages
+		(use twice to suppress error messages too).
+ -h|--help	show this output.
+ -V|--version	show version information.
+
+Examples:
+ $PROGNAME --all --idle
+ $PROGNAME --quiet /dev/md[123]
+ $PROGNAME -sa
+ $PROGNAME -x --all
+
+Devices can be specified in almost any format. The following are equivalent:
+ /dev/md0, md0, /dev/md/0, /sys/block/md0
+
+You can also control the status of a check with /proc/mdstat file."
 }
 
 SHORTOPTS=achVqQsxilf
@@ -76,15 +72,15 @@ for opt in $@; do
     -f|--fast) ionice=high;;
     --realtime) ionice=realtime;;
     -c|--cron) cron=1;;
-    -q|--quiet) quiet=1;;
-    -Q|--real-quiet) quiet=2;;
+    -q|--quiet) quiet=$(($quiet+1));;
+    -Q|--real-quiet) quiet=$(($quiet+2));;	# for compatibility
     -h|--help) usage; exit 0;;
     -V|--version) about; exit 0;;
     /dev/md/*|md/*) arrays="${arrays:+$arrays }md${opt#*md/}";;
     /dev/md*|md*) arrays="${arrays:+$arrays }${opt#/dev/}";;
     /sys/block/md*) arrays="${arrays:+$arrays }${opt#/sys/block/}";;
     --) :;;
-    *) echo "$PROGNAME: E: invalid option: $opt" >&2; usage >&2; exit 0;;
+    *) echo "$PROGNAME: E: invalid option: $opt.  Try --help." >&2; exit 1;;
   esac
 done
 
@@ -139,33 +135,33 @@ fi
 [ $all = 1 ] && arrays="$(ls -d1 /sys/block/md* | cut -d/ -f4)"
 
 for array in $arrays; do
-  SYNC_ACTION_CTL=/sys/block/$array/md/sync_action
+  MDBASE=/sys/block/$array/md
 
-  if [ ! -e $SYNC_ACTION_CTL ]; then
+  if [ ! -e $MDBASE/sync_action ]; then
     [ $quiet -lt 1 ] && echo "$PROGNAME: I: skipping non-redundant array $array." >&2
     continue
   fi
 
-  cur_status="$(cat $SYNC_ACTION_CTL)"
+  read cur_status < $MDBASE/sync_action
 
   if [ $action = status ]; then
     echo "$array: $cur_status"
     continue
   fi
 
-  if [ ! -w $SYNC_ACTION_CTL ]; then
-    [ $quiet -lt 2 ] && echo "$PROGNAME: E: $SYNC_ACTION_CTL not writeable." >&2
+  if [ ! -w $MDBASE/sync_action ]; then
+    [ $quiet -lt 2 ] && echo "$PROGNAME: E: $MDBASE/sync_action not writeable." >&2
     exit 4
   fi
 
-  if [ "$(cat /sys/block/$array/md/array_state)" = 'read-auto' ]; then
-    echo "$PROGNAME: W: array $array in auto-read-only state, skipping..." >&2
+  if [ "$(cat $MDBASE/array_state)" = 'read-auto' ]; then
+    [ $quiet -lt 1 ] && echo "$PROGNAME: W: array $array in auto-read-only state, skipping..." >&2
     continue
   fi
 
   case "$action" in
     idle)
-      echo $action > $SYNC_ACTION_CTL
+      echo $action > $MDBASE/sync_action
       [ $quiet -lt 1 ] && echo "$PROGNAME: I: cancel request queued for array $array." >&2
       ;;
 
@@ -175,16 +171,31 @@ for array in $arrays; do
         continue
       fi
 
+      # check if the array created recently and skip test if it is
+      created=$(mdadm --detail /dev/$array 2>/dev/null |
+                sed -n 's/.*Creation Time *://p' )
+      if [ -n "$created" ]; then
+        created=$(date +%s -d "$created" 2>/dev/null)
+      fi
+      if [ -n "$created" ]; then
+        now=$(date +%s)
+        if [ "$created" -lt "$now" -a \
+             "$created" -gt "$(($now - 14 * 24 * 60 * 60))" ]; then
+          [ $quiet -lt 2 ] && echo "$PROGNAME: I: array $array created recently, skipping..." >&2
+          continue
+        fi
+      fi
+
       # queue request for the array. The kernel will make sure that these requests
       # are properly queued so as to not kill one of the array.
-      echo $action > $SYNC_ACTION_CTL
+      echo $action > $MDBASE/sync_action
       [ $quiet -lt 1 ] && echo "$PROGNAME: I: check queued for array $array." >&2
 
       case "$ionice" in
-        idle) arg='-c3';;
-        low) arg='-c2 -n7';;
-        high) arg='-c2 -n0';;
-        realtime) arg='-c1 -n4';;
+        idle) ioarg='-c3'; renice=15;;
+        low) ioarg='-c2 -n7'; renice=5;;
+        high) ioarg='-c2 -n0'; renice=0;;
+        realtime) ioarg='-c1 -n4'; renice=-5;;
         *) break;;
       esac
 
@@ -193,8 +204,9 @@ for array in $arrays; do
         wait=$((wait - 1))
         resync_pid=$(ps -ef | awk -v dev=$array 'BEGIN { pattern = "^\\[" dev "_resync]$" } $8 ~ pattern { print $2 }')
         if [ -n "$resync_pid" ]; then
-          echo "$PROGNAME: I: selecting $ionice I/O scheduling class for resync of $array." >&2
-          ionice -p "$resync_pid" $arg
+          [ $quiet -lt 1 ] && echo "$PROGNAME: I: selecting $ionice I/O scheduling class and $renice niceness for resync of $array." >&2
+          ionice -p "$resync_pid" $ioarg || :
+          renice -n $renice -p "$resync_pid" 1>/dev/null || :
           break
         fi
         sleep 1
diff --git a/test b/test
--- a/test
+++ b/test
@@ -37,24 +37,27 @@ mdsize1=19992
 mdsize1a=19988
 mdsize12=19988
 # super1.2 for linear: round to multiple of 2, subtract 4
-mdsize1_l=18976
-mdsize2_l=18976
+mdsize1_l=19996
+mdsize2_l=19996
 # subtract another 4 for bitmaps
 mdsize1b=19988
 mdsize11=19992
-mdsize11a=18944
+mdsize11a=19456
 mdsize12=19988
 
 # ddf needs bigger devices as 32Meg is reserved!
 ddfsize=65536
 
+config=/tmp/mdadm.conf
+
 cleanup() {
 	udevadm settle
-	$mdadm -Ssq
+	$mdadm -Ssq 2> /dev/null
 	for d in 0 1 2 3 4 5 6 7  8 9 10 11 12
 	do
-           losetup -d /dev/loop$d ; # rm -f $targetdir/mdtest$d
-        done
+	    losetup -d /dev/loop$d ; # rm -f $targetdir/mdtest$d
+	    rm -f /dev/disk/by-path/loop*
+	done
 }
 
 trap cleanup 0 1 2 3 15
@@ -100,6 +103,9 @@ mdadm() {
         * )   $mdadm 2> $targetdir/stderr --quiet "$@"
     esac
     rv=$?
+    case $* in
+       *-S* ) udevadm settle;;
+    esac
     cat >&2 $targetdir/stderr
     return $rv
 }
@@ -116,45 +122,45 @@ check() {
       ;;
     raid* | linear )
       grep -s "active $1 " /proc/mdstat > /dev/null || {
-   		echo >&2 "ERROR active $1 not found" ; cat /proc/mdstat ; exit 1;}
+		echo >&2 "ERROR active $1 not found" ; cat /proc/mdstat ; exit 1;}
      ;;
     resync | recovery | reshape)
       sleep 0.5
       grep -s $1 /proc/mdstat > /dev/null || {
-   		echo >&2 ERROR no $1 happening; cat /proc/mdstat; exit 1; }
+		echo >&2 ERROR no $1 happening; cat /proc/mdstat; exit 1; }
      ;;
-   
+
      nosync )
        sleep 0.5
-       if grep -s -E '(resync|recovery|reshape) =' > /dev/null /proc/mdstat ; then
-   	   echo >&2 "ERROR resync or recovery is happening!"; cat /proc/mdstat ; exit 1; 
+       if grep -s -E '(resync|recovery|reshape) *=' > /dev/null /proc/mdstat ; then
+		echo >&2 "ERROR resync or recovery is happening!"; cat /proc/mdstat ; exit 1;
        fi
      ;;
-   
+
     wait )
       sleep 0.1
-      while grep -E '(resync|recovery|reshape|check|repair) =' > /dev/null /proc/mdstat
+      while grep -E '(resync|recovery|reshape|check|repair) *=' > /dev/null /proc/mdstat
       do sleep 2;
       done
       ;;
-   
+
     state )
        grep -s "blocks.*\[$2\]\$" /proc/mdstat > /dev/null || {
-   		echo >&2 "ERROR state $2 not found!"; cat /proc/mdstat ; exit 1; }
+		echo >&2 "ERROR state $2 not found!"; cat /proc/mdstat ; exit 1; }
        sleep 0.5
       ;;
 
     bitmap )
        grep -s bitmap > /dev/null /proc/mdstat || {
-	   echo >&2 ERROR no bitmap ; cat /proc/mdstat ; exit 1; }
+		echo >&2 ERROR no bitmap ; cat /proc/mdstat ; exit 1; }
       ;;
     nobitmap )
-       if grep -s "bitmap" > /dev/null /proc/mdstat 
+       if grep -s "bitmap" > /dev/null /proc/mdstat
        then
-	   echo >&2 ERROR bitmap present ; cat /proc/mdstat ; exit 1;
+		echo >&2 ERROR bitmap present ; cat /proc/mdstat ; exit 1;
        fi
       ;;
-   
+
     * ) echo >&2 ERROR unknown check $1 ; exit 1;
    esac
 }
@@ -184,9 +190,10 @@ testdev() {
       rasize=$[rasize*DEV_ROUND_K*2]
    fi
    if [ `/sbin/blockdev --getsize $dev` -eq 0 ]; then sleep 2 ; fi
-   if [ $rasize -ne `/sbin/blockdev --getsize $dev` ]
+   _sz=`/sbin/blockdev --getsize $dev`
+   if [ $rasize -lt $_sz -o $[rasize*4/5] -gt $_sz ]
    then
-     echo "ERROR: size is wrong for $dev: $cnt * $dvsize (chunk=$chunk) = $rasize, not `/sbin/blockdev --getsize $dev`"
+     echo "ERROR: size is wrong for $dev: $cnt * $dvsize (chunk=$chunk) = $rasize, not $_sz"
      exit 1
    fi
 }
@@ -196,42 +203,23 @@ rotest() {
   fsck -fn $dev >&2
 }
 
-setup_environment() {
-   if [ -f $1 ]; then
-      . $environment
-      setup_env
-   fi
-}
-
-reset_environment() {
-   if [ -f $1 ]; then
-      reset_env
-      unset setup_env
-      unset reset_env
-   fi
-}
-
 for script in tests/$prefix tests/$prefix*[^~]
 do
   if [ -f "$script" ]
   then
    rm -f $targetdir/stderr
    # stop all arrays, just incase some script left an array active.
-   mdadm -Ssq
+   $mdadm -Ssq 2> /dev/null
    mdadm --zero $devlist 2> /dev/null
    mdadm --zero $devlist 2> /dev/null
-   environment="tests/env-`basename $script`"
-   setup_environment $environment
    # source script in a subshell, so it has access to our
    # namespace, but cannot change it.
+   echo -ne "$script... "
    if ( set -ex ; . $script )  2> $targetdir/log
-   then echo "$script succeeded" 
-   else cat $targetdir/log ; cat $targetdir/stderr
-        echo "$script failed"
-	reset_environment $environment
+   then echo "succeeded"
+   else echo "FAILED - see $targetdir/log for details"
        exit 1
    fi
-   reset_environment $environment
   fi
 done
 exit 0
